# Generated by Django 4.2.7 on 2023-11-06 15:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Task_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=64)),
                ('Entry_Date', models.DateTimeField(auto_now=True)),
                ('Due_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Finish_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False, editable=False)),
                ('description', models.TextField(default='No description')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('TeamUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignedtask', to='user.todouser')),
                ('Teamleader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.todouser')),
            ],
        ),
        migrations.CreateModel(
            name='Individual_Task',
            fields=[
                ('Task_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=64)),
                ('Entry_Date', models.DateTimeField(auto_now=True)),
                ('Due_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Finish_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False, editable=False)),
                ('description', models.TextField(default='No description')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.todouser')),
            ],
        ),
    ]
