# Generated by Django 4.2.7 on 2023-11-04 14:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('project', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Task_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=64)),
                ('Entry_Date', models.DateTimeField(auto_now=True)),
                ('Due_Date', models.DateTimeField()),
                ('Finish_Date', models.DateTimeField()),
                ('status', models.BooleanField(default=False, editable=False)),
                ('description', models.TextField(default='No description')),
                ('Project_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('TeamUser_ID', models.ManyToManyField(to='user.friend')),
                ('Teamleader_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Individual_Task',
            fields=[
                ('Task_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=64)),
                ('Entry_Date', models.DateTimeField(auto_now=True)),
                ('Due_Date', models.DateTimeField()),
                ('Finish_Date', models.DateTimeField()),
                ('status', models.BooleanField(default=False, editable=False)),
                ('description', models.TextField(default='No description')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
            ],
        ),
    ]
