# Generated by Django 4.2.7 on 2023-11-05 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customer_user_todouser_alter_friend_from_user_and_more'),
        ('task', '0002_alter_individual_task_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual_task',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.todouser'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Teamleader_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.todouser'),
        ),
    ]
