# Generated by Django 4.2.7 on 2023-11-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_status_task_achieve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual_task',
            name='category',
            field=models.CharField(choices=[('due', 'due'), ('pastdue', 'pastdue'), ('complete', 'complete')], default='category1', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('due', 'due'), ('pastdue', 'pastdue'), ('complete', 'complete')], default='category1', max_length=20),
        ),
    ]
