# Generated by Django 4.2.7 on 2023-11-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_team_teamuser_id'),
        ('task', '0003_alter_individual_task_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Project_ID',
            new_name='Project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='TeamUser_ID',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Teamleader_ID',
        ),
        migrations.AddField(
            model_name='task',
            name='Team',
            field=models.ManyToManyField(to='project.team'),
        ),
        migrations.DeleteModel(
            name='Individual_Task',
        ),
    ]
