# Generated by Django 4.2.7 on 2023-11-06 08:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_todouser_friends_delete_friend'),
        ('task', '0004_rename_project_id_task_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual_Task',
            fields=[
                ('Task_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=64)),
                ('Entry_Date', models.DateTimeField(auto_now=True)),
                ('Due_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Finish_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False, editable=False)),
                ('description', models.TextField(default='No description')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.todouser')),
            ],
        ),
    ]
