# Generated by Django 4.2.7 on 2023-11-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_individual_task_category_alter_task_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual_task',
            old_name='status',
            new_name='achieve',
        ),
        migrations.AlterField(
            model_name='individual_task',
            name='category',
            field=models.CharField(choices=[('due', 'due'), ('pastdue', 'pastdue'), ('complete', 'complete')], default='due', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('due', 'due'), ('pastdue', 'pastdue'), ('complete', 'complete')], default='due', max_length=20),
        ),
    ]
