# Generated by Django 4.2.7 on 2023-11-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_rename_status_individual_task_achieve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual_task',
            name='achieve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='achieve',
            field=models.BooleanField(default=False),
        ),
    ]
