# Generated by Django 4.2.7 on 2023-11-06 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_team_teamusers_team_teammember'),
        ('task', '0005_individual_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Team',
        ),
        migrations.AddField(
            model_name='task',
            name='Team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.team'),
        ),
    ]
