# Generated by Django 4.2.7 on 2023-11-06 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_team_teamusers_team_teammember'),
        ('task', '0006_remove_task_team_task_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.team'),
        ),
    ]
