# Generated by Django 4.2.7 on 2023-11-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_individual_task_achieve_alter_task_achieve'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual_task',
            name='count_date',
            field=models.DateTimeField(null=True),
        ),
    ]
