# Generated by Django 4.2.7 on 2023-11-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_individual_task_count_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual_task',
            name='count_date',
        ),
    ]
