# Generated by Django 4.2.7 on 2023-11-06 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_todouser_friends_delete_friend'),
        ('project', '0006_remove_team_teamusers_team_teammember'),
        ('task', '0007_alter_task_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='TaskOwner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_tasks', to='user.todouser'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.team'),
        ),
    ]
