# Generated by Django 4.2.7 on 2023-11-06 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_task_taskowner_alter_task_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Team',
        ),
    ]
