# Generated by Django 4.2.7 on 2023-11-10 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_project_teamuser_remove_project_team_id_and_more'),
        ('task', '0008_remove_individual_task_count_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_project', to='project.project'),
        ),
    ]
