# Generated by Django 4.2.7 on 2023-11-06 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_teamleader_project_teammember_delete_team'),
        ('task', '0009_remove_task_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.project'),
        ),
    ]
