# Generated by Django 4.2.5 on 2023-11-18 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_todouser_image_field'),
        ('task', '0009_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual_task',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Individual_Task', to='user.todouser'),
        ),
    ]
