# Generated by Django 4.2.7 on 2023-11-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_individual_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual_task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='user_files/'),
        ),
    ]
