# Generated by Django 4.2.7 on 2023-11-06 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_todouser_user'),
        ('task', '0010_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual_task',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Individual_Task', to='user.todouser'),
        ),
    ]
