# Generated by Django 4.2.7 on 2023-11-07 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_friend_request'),
        ('task', '0011_alter_individual_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual_task',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_tasks', to='user.todouser'),
        ),
    ]
