# Generated by Django 4.2.7 on 2023-11-04 14:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Project_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Project_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('Team_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Team_name', models.CharField(max_length=64)),
                ('Project_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('TeamLeader_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
                ('TeamUser_ID', models.ManyToManyField(to='user.friend')),
            ],
        ),
    ]
