# Generated by Django 4.2.7 on 2023-11-06 15:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Project_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Project_name', models.CharField(max_length=64)),
                ('Team_ID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('TeamLeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='user.todouser')),
                ('TeamUser', models.ManyToManyField(related_name='teamuser', to='user.todouser')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('Team_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teamID', serialize=False, to='project.project')),
                ('Team_name', models.CharField(max_length=64)),
                ('TeamLeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_leader', to='user.todouser')),
                ('TeamUser', models.ManyToManyField(related_name='user_in_team', to='user.todouser')),
            ],
        ),
    ]
