# Generated by Django 4.2.7 on 2023-11-05 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customer_user_todouser_alter_friend_from_user_and_more'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='TeamLeader_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.todouser'),
        ),
    ]
