# Generated by Django 4.2.7 on 2023-11-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
