# Generated by Django 4.2.7 on 2023-11-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_team_teamleader_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='TeamUser_ID',
        ),
    ]
