# Generated by Django 4.2.7 on 2023-11-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('project', '0003_alter_project_teamuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='TeamUser',
            field=models.ManyToManyField(related_name='teamuser', to='user.todouser'),
        ),
    ]
