# Generated by Django 4.2.7 on 2023-11-06 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_todouser_friends_delete_friend'),
        ('project', '0003_remove_team_teamuser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Project_ID',
            new_name='Project',
        ),
        migrations.RemoveField(
            model_name='team',
            name='TeamLeader_ID',
        ),
        migrations.RemoveField(
            model_name='team',
            name='Team_name',
        ),
        migrations.AddField(
            model_name='team',
            name='TeamLeader',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='TeamLeader', to='user.todouser'),
        ),
        migrations.AddField(
            model_name='team',
            name='TeamUsers',
            field=models.ManyToManyField(default=None, related_name='TeamUsers', to='user.todouser'),
        ),
    ]
