# Generated by Django 4.2.7 on 2023-11-06 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_todouser_friends_delete_friend'),
        ('project', '0004_rename_project_id_team_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='TeamLeader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamLeader', to='user.todouser'),
        ),
        migrations.AlterField(
            model_name='team',
            name='TeamUsers',
            field=models.ManyToManyField(related_name='TeamUsers', to='user.todouser'),
        ),
    ]
