# Generated by Django 4.2.7 on 2023-11-07 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_teamuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='content',
        ),
    ]
