# Generated by Django 4.2.7 on 2023-11-08 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('project', '0005_remove_project_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='TeamUser',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Team_ID',
        ),
        migrations.AddField(
            model_name='project',
            name='TeamMember',
            field=models.ManyToManyField(related_name='TeamMember', to='user.todouser'),
        ),
        migrations.AlterField(
            model_name='project',
            name='TeamLeader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TeamLeader', to='user.todouser'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
