# Generated by Django 4.2.7 on 2023-11-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_todouser_friends_delete_friend'),
        ('project', '0005_alter_team_teamleader_alter_team_teamusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='TeamUsers',
        ),
        migrations.AddField(
            model_name='team',
            name='TeamMember',
            field=models.ManyToManyField(related_name='TeamMember', to='user.todouser'),
        ),
    ]
