# Generated by Django 4.2.7 on 2023-11-06 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_todouser_friends_delete_friend'),
        ('task', '0009_remove_task_team'),
        ('project', '0006_remove_team_teamusers_team_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='TeamLeader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TeamLeader', to='user.todouser'),
        ),
        migrations.AddField(
            model_name='project',
            name='TeamMember',
            field=models.ManyToManyField(related_name='TeamMember', to='user.todouser'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
