# Generated by Django 4.2.7 on 2023-11-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todouser',
            name='image_field',
            field=models.ImageField(default='Django_todo/staticstatic/images/defaultprofile.jpg', upload_to=''),
        ),
    ]
