# Generated by Django 4.2.7 on 2023-11-05 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customer_user_todouser_alter_friend_from_user_and_more'),
        ('task', '0003_alter_individual_task_user_id_and_more'),
        ('project', '0002_alter_team_teamleader_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
