# Generated by Django 4.2.7 on 2023-11-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_team_teamuser_id'),
        ('task', '0004_rename_project_id_task_project_and_more'),
        ('user', '0003_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='todouser',
            name='friends',
            field=models.ManyToManyField(blank=True, to='user.todouser'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
