# Generated by Django 4.2.7 on 2023-11-25 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_forget_pass_forget_id_alter_forget_pass_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forget_pass',
            name='id',
        ),
        migrations.AlterField(
            model_name='forget_pass',
            name='forget_ID',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todouser',
            name='image_field',
            field=models.ImageField(default='user_images/defaultprofile.jpg', upload_to='user_images/'),
        ),
    ]
